name: Flask App CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 020866158197.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Tag Docker Image
      run: |
        docker build -t flask-app .
        docker tag flask-app:latest 020866158197.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

    - name: Push Docker Image to ECR
      run: |
        docker push 020866158197.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

    - name: Set Up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name flask-app-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
